Final Refactors
mrigankpawagi/HinglishEval pull request #73
Opened 2024-12-01 05:29 UTC by SidZRed

Refactored some of the codes by adding some more comments and guidelines.
Modified README for easier use.

IRT scripts may still need some changes. Not exactly sure how much to modify.

2024-12-01 08:48 UTC, AnirudhG07 approved these changes
I think let's merge this! Then any changes suitable, I'll add on to it in a new PR.

2024-12-01 09:01 UTC, mrigankpawagi requested changes

2024-12-01 09:01 UTC, mrigankpawagi commented on README.md
I will go over the README again after you fix things in this PR.

In principle, you can first fix & merge the README and later we can improve the scripts. But this is okay. 

If @AnirudhG07 wants to push other changes, better to make another PR to main (we will resolve conflicts) or make a PR to *this* PR's branch (preferable if Anirudh's changes are quicker).

2024-12-01 09:08 UTC, SidZRed commented on irt/irt_eval.py
> +        if model in ["codegen2_1B", "santacoder"]:    # Skipt these 2 models.
They had some issues of non completion (atleast for us) or something right @AnirudhG07

2024-12-01 09:11 UTC, SidZRed commented on samples/requirements.txt
> +openai
If someone only wants to use the evaluator functions without the need for certain models, then it is fine to have 2 I guess?

2024-12-01 09:11 UTC, SidZRed commented on irt/irt_eval.py
> +    write_csv(f"./irt_ratings/{output_name}_sorted_irt_itemparams.csv", sorted_item_csv_data)
Right, I'll change it everywhere

2024-12-01 09:12 UTC, AnirudhG07 commented on irt/irt_eval.py
> +        if model in ["codegen2_1B", "santacoder"]:    # Skipt these 2 models.
because there generations were messed up when running the 2nd time. We removed these models from our evaluations

2024-12-01 09:14 UTC, AnirudhG07 commented on samples/codemodels/gpt.py
I will add that once this is merged and use `dotenv` for everything. Will also test its workings.

2024-12-01 09:14 UTC, AnirudhG07 commented on samples/codemodels/gpt.py
> +        model="gpt-3.5-turbo",  # Change to GPT-4 if necessary
lets put link to all models which can be inputted here. since the casing and spelling of the models matter.

2024-12-01 09:15 UTC, AnirudhG07 commented on samples/requirements.txt
> +openai
yes agreed. Since requirements should be good enough. 
Ill also add a part on how to reproduce the results.

2024-12-01 09:16 UTC, AnirudhG07 commented on README.md
> +- **Unsanitized Completions**: Found in the `samples/unsanitized` directory, these are raw outputs generated by the models without any post-processing.
Should give link to released I guess

2024-12-01 09:17 UTC, AnirudhG07 commented on README.md
umm. I would need to make good amounts of changes. Better to make a new PR. Ill not make any changes to README

2024-12-01 10:45 UTC, mrigankpawagi commented on irt/irt_eval.py
> +        if model in ["codegen2_1B", "santacoder"]:    # Skipt these 2 models.
hmm... but we still provide those model samples?

2024-12-01 11:52 UTC, SidZRed commented
I have made changes other than for README
We can merge this and look at the README and release specifications later after other changes are made.

2024-12-01 15:47 UTC, SidZRed commented
OK all env files and README updations are merged into this PR.
I shall have a review of the scripts and remaining IRT files and clear this PR soon.

2024-12-02 06:23 UTC, mrigankpawagi commented
`.env` must always be ignored. 

Going over other changes currently.

2024-12-02 08:00 UTC, mrigankpawagi commented
@AnirudhG07 can you fix "Running the code" part of Usage to use the releases (maybe mention where to place the release ZIPs, etc.) instead of assuming that the code is already in `samples/`? Also can you add a short note on running the code for generating translations (also part of "reproduction")

2024-12-02 08:36 UTC, AnirudhG07 commented
Done. Made some changes. although I didnt feel like anything else is to be added. If you think, then you can add.

2024-12-02 10:29 UTC, mrigankpawagi approved these changes

2024-12-02 10:29 UTC, merged